baseURL: "https://theuselessweb.com/sites"
languageCode: en-us
title: "The Useless Web"
paginate: 4
paginatePath: ''
disableKinds: ["taxonomy", "taxonomyTerm"]
permalinks:
  sites: /:slug
markup:
  goldmark:
    renderer:
      unsafe: true
